language: go
go_import_path: github.com/gallactic/gallactic
sudo: false

services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty
      go: 1.10.x
      script: make && macke docker
      
    - os: linux
      dist: trusty
      go: master
      script: make
      
    - os: osx
      go: 1.10.x
      script: make
      
    - os: osx
      go: master
      script: make
      
    - os: windows
      go: 1.10.x
      script: mingw32-make
      
    - os: windows
      go: master
      script: mingw32-make 


before_install:
  # installing rust and cargo
  - curl -sSf rustup-install.sh https://sh.rustup.rs > rustup-install.sh
  - sh rustup-install.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"

deploy:
  provider: releases
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.10
